# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kevin Hegel
description:  "If I could be any kind of computer, I would be a supercomputer" 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kevinhegel.com" # the base hostname & protocol for your site, e.g. http://example.com
remote_theme: kevinbagel/kevin-hegel-site-uno
#theme: jekyll-uno-test
google_analytics: 'UA-175647195-1'
disqus_shortname: 'kevinhegel'
author:
  name: 'Kevin Hegel'
  email: k@kevinhegel.com
  #twitter_username: empty
  #facebook_username: empty
  github_username: kevinbagel
  linkedin_username: kjhegel
  pgp_key: pgp.txt

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed


kramdown:
  #use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-include-cache



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .travis.yml
  - README.md
  - vendor
